//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngenieriaVisualPH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaldo
    {
        public string Codigo { get; set; }
        public string Admi { get; set; }
        public string Favor { get; set; }
        public string Inter { get; set; }
        public string Sancion { get; set; }
        public string Moto { get; set; }
        public string Carro { get; set; }
        public string Total { get; set; }
        public string Juridico { get; set; }
    }
}
